/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.0.2.0                                               */
/*  Date (dd.mm.yyyy):  5. 9.2020   Time (hh:mm): 18:56                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "display_bitmap_resources.h"
#include "display_bitmap_specifications.h"

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
WINDOW_CONTROL_BLOCK window;
GX_DISPLAY display_1_control_block;
GX_WINDOW_ROOT display_1_root_window;
GX_CANVAS  display_1_canvas_control_block;
ULONG      display_1_canvas_memory[95250];

extern GX_CONST GX_THEME *display_1_theme_table[];
extern GX_CONST GX_STRING *display_1_language_table[];

GX_STUDIO_DISPLAY_INFO display_bitmap_display_table[1] =
{
    {
    "display_1",
    "display_1_canvas",
    display_1_theme_table,
    display_1_language_table,
    DISPLAY_1_THEME_TABLE_SIZE,
    DISPLAY_1_LANGUAGE_TABLE_SIZE,
    DISPLAY_1_STRING_TABLE_SIZE,
    381,                                     /* x resolution                   */
    500,                                     /* y resolution                   */
    &display_1_control_block,
    &display_1_canvas_control_block,
    &display_1_root_window,
    display_1_canvas_memory,                 /* canvas memory area             */
    381000                                   /* canvas memory size in bytes    */
    }
};


UINT gx_studio_icon_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_ICON_BUTTON *button = (GX_ICON_BUTTON *) control_block;
    GX_ICON_BUTTON_PROPERTIES *props = (GX_ICON_BUTTON_PROPERTIES *) info->properties;
    status = gx_icon_button_create(button, info->widget_name, parent, props->pixelmap_id, info->style, info->widget_id, &info->size);
    return status;
}

UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_WINDOW *window = (GX_WINDOW *) control_block;
    GX_WINDOW_PROPERTIES *props = (GX_WINDOW_PROPERTIES *) info->properties;
    status = gx_window_create(window, info->widget_name, parent, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        if (props->wallpaper_id)
        {
            gx_window_wallpaper_set(window, props->wallpaper_id, info->style & GX_STYLE_TILE_WALLPAPER);
        }
    }
    return status;
}
GX_WINDOW_PROPERTIES window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES window_canvas_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_VERSION_NUMBER_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_VERSION_NUMBER      /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_STYLE_SWITCH_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_STYLE_SWITCH        /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_ECG_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_ECG                 /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_STOPWATCH_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_STOPWATCH           /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_Contact_PERSON_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_CONTACT_PERSON      /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_QR_CODE_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_QR_CODE             /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_CALL_RECORDS_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_CALL_RECORDS        /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_TAKE_PICTURES_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_TAKE_PICTURES       /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_DIAL_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_DIAL                /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_BLOOD_OXYGEN_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_BLOOD_OXYGEN        /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_METRONOME_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_METRONOME           /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_FIND_PHONE_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_FIND_PHONE          /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_BLOOD_PROESSURE_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_BLOOD_PRESSURE      /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_CENTER_TABLE_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_CENTER_TABLE        /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_RUN_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_RUN                 /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_DIMMING_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_DIMMING             /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_SOS_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_SOS                 /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_NEWS_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_NEWS                /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_HEART_RATE_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_HEART_RATE          /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_THE_WEATHER_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_THE_WEATHER         /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_SHUTDOWN_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_SHUTDOWN            /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_MUSIC_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_MUSIC               /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_SLEEP_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_SLEEP               /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_RELAX_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_RELAX               /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_RESET_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_RESET               /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_NATIONAL_LANGUAGE_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_NATIONAL_LANGUAGE   /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES window_IDC_INCOMING_CALL_SETTINGS_67x67_properties =
{
    GX_PIXELMAP_ID_ICON3_INCOMING_CALL_SETTINGS  /* pixelmap id                */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_INCOMING_CALL_SETTINGS_67x67_define =
{
    "IDC_INCOMING_CALL_SETTINGS_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_INCOMING_CALL_SETTINGS_67x67,        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {230, 432, 296, 498},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_INCOMING_CALL_SETTINGS_67x67), /* control block */
    (void *) &window_IDC_INCOMING_CALL_SETTINGS_67x67_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_NATIONAL_LANGUAGE_67x67_define =
{
    "IDC_NATIONAL_LANGUAGE_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_NATIONAL_LANGUAGE_67x67,             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {96, 432, 162, 498},                     /* widget size                    */
    &window_IDC_INCOMING_CALL_SETTINGS_67x67_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_NATIONAL_LANGUAGE_67x67), /* control block */
    (void *) &window_IDC_NATIONAL_LANGUAGE_67x67_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_RESET_67x67_define =
{
    "IDC_RESET_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_RESET_67x67,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {314, 358, 380, 424},                    /* widget size                    */
    &window_IDC_NATIONAL_LANGUAGE_67x67_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_RESET_67x67), /* control block   */
    (void *) &window_IDC_RESET_67x67_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_RELAX_67x67_define =
{
    "IDC_RELAX_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_RELAX_67x67,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {241, 359, 307, 425},                    /* widget size                    */
    &window_IDC_RESET_67x67_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_RELAX_67x67), /* control block   */
    (void *) &window_IDC_RELAX_67x67_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_SLEEP_67x67_define =
{
    "IDC_SLEEP_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_SLEEP_67x67,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {163, 376, 229, 442},                    /* widget size                    */
    &window_IDC_RELAX_67x67_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_SLEEP_67x67), /* control block   */
    (void *) &window_IDC_SLEEP_67x67_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_MUSIC_67x67_define =
{
    "IDC_MUSIC_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_MUSIC_67x67,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {85, 359, 151, 425},                     /* widget size                    */
    &window_IDC_SLEEP_67x67_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_MUSIC_67x67), /* control block   */
    (void *) &window_IDC_MUSIC_67x67_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_SHUTDOWN_67x67_define =
{
    "IDC_SHUTDOWN_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_SHUTDOWN_67x67,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {12, 358, 78, 424},                      /* widget size                    */
    &window_IDC_MUSIC_67x67_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_SHUTDOWN_67x67), /* control block */
    (void *) &window_IDC_SHUTDOWN_67x67_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_THE_WEATHER_67x67_define =
{
    "IDC_THE_WEATHER_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_THE_WEATHER_67x67,                   /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {285, 287, 351, 353},                    /* widget size                    */
    &window_IDC_SHUTDOWN_67x67_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_THE_WEATHER_67x67), /* control block */
    (void *) &window_IDC_THE_WEATHER_67x67_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_HEART_RATE_67x67_define =
{
    "IDC_HEART_RATE_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_HEART_RATE_67x67,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {197, 287, 263, 353},                    /* widget size                    */
    &window_IDC_THE_WEATHER_67x67_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_HEART_RATE_67x67), /* control block */
    (void *) &window_IDC_HEART_RATE_67x67_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_NEWS_67x67_define =
{
    "IDC_NEWS_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_NEWS_67x67,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {118, 287, 184, 353},                    /* widget size                    */
    &window_IDC_HEART_RATE_67x67_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_NEWS_67x67), /* control block    */
    (void *) &window_IDC_NEWS_67x67_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_SOS_67x67_define =
{
    "IDC_SOS_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_SOS_67x67,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {32, 287, 98, 353},                      /* widget size                    */
    &window_IDC_NEWS_67x67_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_SOS_67x67), /* control block     */
    (void *) &window_IDC_SOS_67x67_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_DIMMING_67x67_define =
{
    "IDC_DIMMING_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_DIMMING_67x67,                       /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {313, 216, 379, 282},                    /* widget size                    */
    &window_IDC_SOS_67x67_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_DIMMING_67x67), /* control block */
    (void *) &window_IDC_DIMMING_67x67_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_RUN_67x67_define =
{
    "IDC_RUN_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_RUN_67x67,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {230, 216, 296, 282},                    /* widget size                    */
    &window_IDC_DIMMING_67x67_define,        /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_RUN_67x67), /* control block     */
    (void *) &window_IDC_RUN_67x67_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_CENTER_TABLE_67x67_define =
{
    "IDC_CENTER_TABLE_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_CENTER_TABLE_67x67,                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {159, 216, 225, 282},                    /* widget size                    */
    &window_IDC_RUN_67x67_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_CENTER_TABLE_67x67), /* control block */
    (void *) &window_IDC_CENTER_TABLE_67x67_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_BLOOD_PROESSURE_67x67_define =
{
    "IDC_BLOOD_PROESSURE_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_BLOOD_PROESSURE_67x67,               /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {83, 216, 149, 282},                     /* widget size                    */
    &window_IDC_CENTER_TABLE_67x67_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_BLOOD_PROESSURE_67x67), /* control block */
    (void *) &window_IDC_BLOOD_PROESSURE_67x67_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_FIND_PHONE_67x67_define =
{
    "IDC_FIND_PHONE_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_FIND_PHONE_67x67,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {0, 216, 66, 282},                       /* widget size                    */
    &window_IDC_BLOOD_PROESSURE_67x67_define, /* next widget definition        */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_FIND_PHONE_67x67), /* control block */
    (void *) &window_IDC_FIND_PHONE_67x67_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_METRONOME_67x67_define =
{
    "IDC_METRONOME_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_METRONOME_67x67,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {280, 145, 346, 211},                    /* widget size                    */
    &window_IDC_FIND_PHONE_67x67_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_METRONOME_67x67), /* control block */
    (void *) &window_IDC_METRONOME_67x67_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_BLOOD_OXYGEN_67x67_define =
{
    "IDC_BLOOD_OXYGEN_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_BLOOD_OXYGEN_67x67,                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {197, 145, 263, 211},                    /* widget size                    */
    &window_IDC_METRONOME_67x67_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_BLOOD_OXYGEN_67x67), /* control block */
    (void *) &window_IDC_BLOOD_OXYGEN_67x67_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_DIAL_67x67_define =
{
    "IDC_DIAL_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_DIAL_67x67,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {119, 144, 185, 210},                    /* widget size                    */
    &window_IDC_BLOOD_OXYGEN_67x67_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_DIAL_67x67), /* control block    */
    (void *) &window_IDC_DIAL_67x67_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_TAKE_PICTURES_67x67_define =
{
    "IDC_TAKE_PICTURES_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_TAKE_PICTURES_67x67,                 /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {36, 144, 102, 210},                     /* widget size                    */
    &window_IDC_DIAL_67x67_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_TAKE_PICTURES_67x67), /* control block */
    (void *) &window_IDC_TAKE_PICTURES_67x67_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_CALL_RECORDS_67x67_define =
{
    "IDC_CALL_RECORDS_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_CALL_RECORDS_67x67,                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {312, 74, 378, 140},                     /* widget size                    */
    &window_IDC_TAKE_PICTURES_67x67_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_CALL_RECORDS_67x67), /* control block */
    (void *) &window_IDC_CALL_RECORDS_67x67_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_QR_CODE_67x67_define =
{
    "IDC_QR_CODE_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_QR_CODE_67x67,                       /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {239, 74, 305, 140},                     /* widget size                    */
    &window_IDC_CALL_RECORDS_67x67_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_QR_CODE_67x67), /* control block */
    (void *) &window_IDC_QR_CODE_67x67_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_Contact_PERSON_67x67_define =
{
    "IDC_Contact_PERSON_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_Contact_PERSON_67x67,                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {161, 57, 227, 123},                     /* widget size                    */
    &window_IDC_QR_CODE_67x67_define,        /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_Contact_PERSON_67x67), /* control block */
    (void *) &window_IDC_Contact_PERSON_67x67_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_STOPWATCH_67x67_define =
{
    "IDC_STOPWATCH_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_STOPWATCH_67x67,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {81, 73, 147, 139},                      /* widget size                    */
    &window_IDC_Contact_PERSON_67x67_define, /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_STOPWATCH_67x67), /* control block */
    (void *) &window_IDC_STOPWATCH_67x67_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_ECG_67x67_define =
{
    "IDC_ECG_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_ECG_67x67,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {8, 73, 74, 139},                        /* widget size                    */
    &window_IDC_STOPWATCH_67x67_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_ECG_67x67), /* control block     */
    (void *) &window_IDC_ECG_67x67_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_STYLE_SWITCH_67x67_define =
{
    "IDC_STYLE_SWITCH_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_STYLE_SWITCH_67x67,                  /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {228, 1, 294, 67},                       /* widget size                    */
    &window_IDC_ECG_67x67_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_STYLE_SWITCH_67x67), /* control block */
    (void *) &window_IDC_STYLE_SWITCH_67x67_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET window_IDC_VERSION_NUMBER_67x67_define =
{
    "IDC_VERSION_NUMBER_67x67",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    IDC_VERSION_NUMBER_67x67,                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    (VOID (*)(GX_WIDGET *)) custom_pixelmap_button_draw, /* drawing function override */
    GX_NULL,                                 /* event function override        */
    {94, 1, 160, 67},                        /* widget size                    */
    &window_IDC_STYLE_SWITCH_67x67_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WINDOW_CONTROL_BLOCK, window_IDC_VERSION_NUMBER_67x67), /* control block */
    (void *) &window_IDC_VERSION_NUMBER_67x67_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET window_canvas_define =
{
    "canvas",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    GX_COLOR_ID_CANVAS,                      /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) canvas_event_handler, /* event function override */
    {0, 0, 380, 499},                        /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    &window_IDC_VERSION_NUMBER_67x67_define, /* child widget definition        */
    offsetof(WINDOW_CONTROL_BLOCK, window_canvas), /* control block            */
    (void *) &window_canvas_properties       /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_define =
{
    "window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(WINDOW_CONTROL_BLOCK),            /* control block size             */
    GX_COLOR_ID_BTN_TEXT,                    /* normal color id                */
    GX_COLOR_ID_CANVAS,                      /* selected color id              */
    GX_COLOR_ID_TEXT,                        /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 380, 499},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &window_canvas_define,                   /* child widget                   */
    0,                                       /* control block                  */
    (void *) &window_properties              /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY display_bitmap_widget_table[] =
{
    { &window_define, (GX_WIDGET *) &window },
    {GX_NULL, GX_NULL}
};

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_WIDGET *widget = GX_NULL;
    GX_VALUE   list_count = 0;
    GX_VALUE   list_total_count = 0;

    if(parent && (parent->gx_widget_type == GX_TYPE_MENU))
    {
        list_total_count = ((GX_MENU *)parent)->gx_menu_list_total_count;
    }

    while(definition && status == GX_SUCCESS)
    {
        if (definition->create_function)
        {
            if (definition->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
            {
                status = gx_widget_allocate(&widget, definition->control_block_size);
                if (status != GX_SUCCESS)
                {
                    return GX_NULL;
                }
            }
            else
            {
                if (control == GX_NULL)
                {
                    return GX_NULL;
                }
                widget = (GX_WIDGET *) (control + definition->control_block_offset);
            }

            status = definition->create_function(definition, widget, parent);

            if(list_count < list_total_count)
            {
                gx_menu_insert((GX_MENU *)parent, widget);
                ((GX_MENU *)parent)->gx_menu_list_total_count--;
                list_count++;
            }

            if (status == GX_SUCCESS)
            {
                if (definition->widget_type != GX_TYPE_TEMPLATE)
                {
#if defined(GUIX_5_4_0_COMPATIBILITY)
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id);
#else
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id, definition->disabled_fill_color_id);
#endif
                }

                if (!(definition->status & GX_STATUS_ACCEPTS_FOCUS))
                {
                    gx_widget_status_remove(widget, GX_STATUS_ACCEPTS_FOCUS);
                }

                if (definition->draw_function)
                {
                    gx_widget_draw_set(widget, definition->draw_function);
                }
                if (definition->event_function)
                {
                    gx_widget_event_process_set(widget, definition->event_function);
                }

                #if defined(GX_WIDGET_USER_DATA)
                widget->gx_widget_user_data = definition->user_data;
                #endif

                if (definition->child_widget)
                {
                    gx_studio_nested_widget_create(control, definition->child_widget, widget);
                }
            }
            definition = definition->next_widget;
        }
    }
    return widget;
}

GX_WIDGET *gx_studio_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    GX_WIDGET *widget;
    widget = gx_studio_nested_widget_create(control, definition, GX_NULL);

    if (parent && widget)
    {
        gx_widget_attach(parent, widget);
    }
    return widget;
}

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    UINT status = GX_FAILURE;
    GX_CONST GX_STUDIO_WIDGET_ENTRY *entry = display_bitmap_widget_table;
    GX_WIDGET *widget = GX_NULL;

    while(entry->widget_information)
    {
        if (!strcmp(name, entry->widget_information->widget_name))
        {
            widget = gx_studio_widget_create((GX_BYTE *) entry->widget, entry->widget_information, parent);
            if (widget)
            {
                status = GX_SUCCESS;
            }
            break;
        }
        entry++;
    }

    if (new_widget)
    {
        *new_widget = widget;
    }
    return status;
}


UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_CONST GX_THEME *theme_ptr;
    GX_RECTANGLE size;

    GX_STUDIO_DISPLAY_INFO *display_info = &display_bitmap_display_table[display];


/* create the requested display                                                */

    gx_display_create(display_info->display,
                      display_info->name,
                      driver,
                      (GX_VALUE) display_info->x_resolution,
                      (GX_VALUE) display_info->y_resolution);


/* install the request theme                                                   */

    if(display_info->theme_table)
    {
        theme_ptr = display_info->theme_table[theme];
        if(theme_ptr)
        {
            gx_display_color_table_set(display_info->display, theme_ptr->theme_color_table, theme_ptr->theme_color_table_size);
            
/* install the color palette if required                                       */
            if (display_info->display->gx_display_driver_palette_set &&
                theme_ptr->theme_palette != NULL)
            {
                display_info->display->gx_display_driver_palette_set(display_info->display, theme_ptr->theme_palette, theme_ptr->theme_palette_size);
            }

            gx_display_font_table_set(display_info->display, theme_ptr->theme_font_table, theme_ptr->theme_font_table_size);
            gx_display_pixelmap_table_set(display_info->display, theme_ptr->theme_pixelmap_table, theme_ptr->theme_pixelmap_table_size);
            gx_system_scroll_appearance_set(theme_ptr->theme_vertical_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_vertical_scrollbar_appearance);
            gx_system_scroll_appearance_set(theme_ptr->theme_horizontal_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_horizontal_scrollbar_appearance);
            gx_display_language_table_set_ext(display_info->display, display_info->language_table, (GX_UBYTE) display_info->language_table_size, display_info->string_table_size);
            gx_display_active_language_set(display_info->display, language);
        }
    }


/* create the canvas for this display                                          */

    gx_canvas_create(display_info->canvas,
                     display_info->canvas_name,
                     display_info->display,
                     GX_CANVAS_MANAGED | GX_CANVAS_VISIBLE,
                     display_info->x_resolution,
                     display_info->y_resolution,
                     display_info->canvas_memory,
                     display_info->canvas_memory_size);

/* Create the root window for this canvas                                      */

    gx_utility_rectangle_define(&size,
                                0, 0,
                                (GX_VALUE) (display_info->x_resolution - 1),
                                (GX_VALUE) (display_info->y_resolution - 1));

    gx_window_root_create(display_info->root_window,
                          display_info->name,
                          display_info->canvas, GX_STYLE_NONE, 0, &size);
    if (return_root)
    {
        *return_root = display_info->root_window;
    }
    return GX_SUCCESS;
}
#undef GUIX_STUDIO_GENERATED_FILE
