/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.0.2.0                                               */
/*  Date (dd.mm.yyyy):  5. 9.2020   Time (hh:mm): 18:56                        */
/*******************************************************************************/


#ifndef _DISPLAY_BITMAP_DISPLAY_1_RESOURCES_H_
#define _DISPLAY_BITMAP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 381
#define DISPLAY_1_Y_RESOLUTION 500
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_ICON1_BLOOD_OXYGEN 5
#define GX_PIXELMAP_ID_ICON1_BLOOD_PRESSURE 6
#define GX_PIXELMAP_ID_ICON1_CALL_RECORDS 7
#define GX_PIXELMAP_ID_ICON1_CENTER_TABLE 8
#define GX_PIXELMAP_ID_ICON1_CONTACT_PERSON 9
#define GX_PIXELMAP_ID_ICON1_DIAL 10
#define GX_PIXELMAP_ID_ICON1_DIMMING 11
#define GX_PIXELMAP_ID_ICON1_ECG 12
#define GX_PIXELMAP_ID_ICON1_FIND_PHONE 13
#define GX_PIXELMAP_ID_ICON1_HEART_RATE 14
#define GX_PIXELMAP_ID_ICON1_INCOMING_CALL_SETTINGS 15
#define GX_PIXELMAP_ID_ICON1_METRONOME 16
#define GX_PIXELMAP_ID_ICON1_MUSIC 17
#define GX_PIXELMAP_ID_ICON1_NATIONAL_LANGUAGE 18
#define GX_PIXELMAP_ID_ICON1_NEWS 19
#define GX_PIXELMAP_ID_ICON1_QR_CODE 20
#define GX_PIXELMAP_ID_ICON1_RELAX 21
#define GX_PIXELMAP_ID_ICON1_RESET 22
#define GX_PIXELMAP_ID_ICON1_RUN 23
#define GX_PIXELMAP_ID_ICON1_SHUTDOWN 24
#define GX_PIXELMAP_ID_ICON1_SLEEP 25
#define GX_PIXELMAP_ID_ICON1_SOS 26
#define GX_PIXELMAP_ID_ICON1_STOPWATCH 27
#define GX_PIXELMAP_ID_ICON1_STYLE_SWITCH 28
#define GX_PIXELMAP_ID_ICON1_TAKE_PICTURES 29
#define GX_PIXELMAP_ID_ICON1_THE_WEATHER 30
#define GX_PIXELMAP_ID_ICON1_VERSION_NUMBER 31
#define GX_PIXELMAP_ID_ICON2_BLOOD_OXYGEN 32
#define GX_PIXELMAP_ID_ICON2_BLOOD_PRESSURE 33
#define GX_PIXELMAP_ID_ICON2_CALL_RECORDS 34
#define GX_PIXELMAP_ID_ICON2_CENTER_TABLE 35
#define GX_PIXELMAP_ID_ICON2_CONTACT_PERSON 36
#define GX_PIXELMAP_ID_ICON2_DIAL 37
#define GX_PIXELMAP_ID_ICON2_DIMMING 38
#define GX_PIXELMAP_ID_ICON2_ECG 39
#define GX_PIXELMAP_ID_ICON2_FIND_PHONE 40
#define GX_PIXELMAP_ID_ICON2_HEART_RATE 41
#define GX_PIXELMAP_ID_ICON2_INCOMING_CALL_SETTINGS 42
#define GX_PIXELMAP_ID_ICON2_METRONOME 43
#define GX_PIXELMAP_ID_ICON2_MUSIC 44
#define GX_PIXELMAP_ID_ICON2_NATIONAL_LANGUAGE 45
#define GX_PIXELMAP_ID_ICON2_NEWS 46
#define GX_PIXELMAP_ID_ICON2_QR_CODE 47
#define GX_PIXELMAP_ID_ICON2_RELAX 48
#define GX_PIXELMAP_ID_ICON2_RESET 49
#define GX_PIXELMAP_ID_ICON2_RUN 50
#define GX_PIXELMAP_ID_ICON2_SHUTDOWN 51
#define GX_PIXELMAP_ID_ICON2_SLEEP 52
#define GX_PIXELMAP_ID_ICON2_SOS 53
#define GX_PIXELMAP_ID_ICON2_STOPWATCH 54
#define GX_PIXELMAP_ID_ICON2_STYLE_SWITCH 55
#define GX_PIXELMAP_ID_ICON2_TAKE_PICTURES 56
#define GX_PIXELMAP_ID_ICON2_THE_WEATHER 57
#define GX_PIXELMAP_ID_ICON2_VERSION_NUMBER 58
#define GX_PIXELMAP_ID_ICON3_BLOOD_OXYGEN 59
#define GX_PIXELMAP_ID_ICON3_BLOOD_PRESSURE 60
#define GX_PIXELMAP_ID_ICON3_CALL_RECORDS 61
#define GX_PIXELMAP_ID_ICON3_CENTER_TABLE 62
#define GX_PIXELMAP_ID_ICON3_CONTACT_PERSON 63
#define GX_PIXELMAP_ID_ICON3_DIAL 64
#define GX_PIXELMAP_ID_ICON3_DIMMING 65
#define GX_PIXELMAP_ID_ICON3_ECG 66
#define GX_PIXELMAP_ID_ICON3_FIND_PHONE 67
#define GX_PIXELMAP_ID_ICON3_HEART_RATE 68
#define GX_PIXELMAP_ID_ICON3_INCOMING_CALL_SETTINGS 69
#define GX_PIXELMAP_ID_ICON3_METRONOME 70
#define GX_PIXELMAP_ID_ICON3_MUSIC 71
#define GX_PIXELMAP_ID_ICON3_NATIONAL_LANGUAGE 72
#define GX_PIXELMAP_ID_ICON3_NEWS 73
#define GX_PIXELMAP_ID_ICON3_QR_CODE 74
#define GX_PIXELMAP_ID_ICON3_RELAX 75
#define GX_PIXELMAP_ID_ICON3_RESET 76
#define GX_PIXELMAP_ID_ICON3_RUN 77
#define GX_PIXELMAP_ID_ICON3_SHUTDOWN 78
#define GX_PIXELMAP_ID_ICON3_SLEEP 79
#define GX_PIXELMAP_ID_ICON3_SOS 80
#define GX_PIXELMAP_ID_ICON3_STOPWATCH 81
#define GX_PIXELMAP_ID_ICON3_STYLE_SWITCH 82
#define GX_PIXELMAP_ID_ICON3_TAKE_PICTURES 83
#define GX_PIXELMAP_ID_ICON3_THE_WEATHER 84
#define GX_PIXELMAP_ID_ICON3_VERSION_NUMBER 85
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 86

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define DISPLAY_1_STRING_TABLE_SIZE 3

#endif                                       /* sentry                         */
